version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
  file:
    class: logging.handlers.WatchedFileHandler
    formatter: simple
    filename: output.log
loggers:
  optimizers:
    level: INFO
    handlers: [console, file]
    propagate: no
  bin:
    level: INFO
    handlers: [console, file]
    propagate: no
  pypet:
    level: ERROR
    handlers: [console, file]
    propagate: no
root:
  level: INFO
  handlers: [console, file]
